### PR TITLE
Fixed VM not booting

### PR DESCRIPTION
**Pull request by provokateurin**

### CODE REVIEW

**Comment by hkdb** [comment]
Do we know if it matters what CPU you actually have and any side affect from setting this CPU profile? Have you tried using this on different hosts? 

"Intel Core i7-6700K"

Thanks for the PR!

**Comment by provokateurin** [comment]
I only tried it on my work machine, but I saw other people who got the same error.

**Comment by hkdb** [comment]
My only concern which I am not sure if it's even a valid concern is whether or not there are any negative implications for someone running on a lower end processor but setting a i7-k processor profile. I am going to merge your PR and then give it a go on one of my i5 machines.

Thanks!

**Comment by hkdb** [comment]
Just tested last night and it looks like the only way to boot is to not set CPU profile and choose OS type "macOS 64-bit" on my i5-4440/16GB of RAM.

**Comment by hkdb** [comment]
Created a branch [set-cpu](https://github.com/hkdb/VBoxMacSetup/tree/set-cpu) and reverted the merge in develop. It probably needs more work before it can be merged in. I would like solutions to go in only if it covers all basis. Thanks!

**Comment by hkdb** [comment]
Put in a more permanent fix at: https://github.com/hkdb/VBoxMacSetup/releases/tag/v1.2

**Pull request merged**
